<a href="https://colab.research.google.com/github/IBREEZZ/Code_Academy_Makeen2/blob/main/week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np

In [28]:
l1=[1,2,3,4]
print(l1)

[1, 2, 3, 4]


In [29]:
arry1=np.array(l1)
print(arry1)
arry1.dtype


[1 2 3 4]


dtype('int64')

In [30]:
l2=[11,22,23,44]
l2

[11, 22, 23, 44]

In [31]:
l=[l1,l2]
l

[[1, 2, 3, 4], [11, 22, 23, 44]]

In [32]:
array_2D=np.array(l)
print(array_2D)

[[ 1  2  3  4]
 [11 22 23 44]]


In [33]:
array_2D.shape

(2, 4)

In [34]:
np.zeros(3,'int')

array([0, 0, 0])

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [36]:
np.zeros([3,2],'int')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [37]:
np.ones(3)

array([1., 1., 1.])

In [38]:
np.ones(3,'int')

array([1, 1, 1])

In [39]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.empty(2)

array([4.94065646e-324, 6.95257087e-310])

In [41]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [42]:
np.empty(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [46]:
arr1=np.array([[1,2,3,4],[8,9,10,11]])
print(arr1)

[[ 1  2  3  4]
 [ 8  9 10 11]]


In [47]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [48]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [49]:
arr3=np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


In [50]:
#error becuse should be same data size (same  shape)
# arr2*arr3

In [51]:
arr1-2

array([[-1,  0,  1,  2],
       [ 6,  7,  8,  9]])

In [52]:
arr1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [53]:
arr1.T

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11]])

In [54]:
A=np.array([[1,2,3],[4,5,6]])
print(A)
print('\n')
B=np.array([[7,8],[9,10],[11,12]])
print(B)
print('\n')
np.dot(A,B)

[[1 2 3]
 [4 5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]




array([[ 58,  64],
       [139, 154]])

In [55]:
a1=np.array([1,3,5])
print(a1)

a2=np.array([2,4,6])
print(a2)

print("add",a1+a2)
print("sub",a1-a2)
print("mul",a1*a2)
print("div",a1/a2)

[1 3 5]
[2 4 6]
add [ 3  7 11]
sub [-1 -1 -1]
mul [ 2 12 30]
div [0.5        0.75       0.83333333]


In [56]:
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [57]:
arr.shape

(11,)

In [58]:
arr[9]

np.int64(9)

In [59]:
arr[1:5]

array([1, 2, 3, 4])

In [60]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [61]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [62]:
slice_of_arr=arr[0:5]
slice_of_arr

array([100, 100, 100, 100, 100])

In [63]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99])

In [64]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [65]:
arr_copy =arr[6:9].copy()
arr_copy

array([6, 7, 8])

In [66]:
arr_copy[:]=0
arr_copy

array([0, 0, 0])

In [67]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [68]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
arr_2d[1]

array([20, 25, 30])

In [70]:
arr_2d[:,1]

array([10, 25, 40])

In [79]:
print(arr_2d[1][2])

30


In [72]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [73]:
arr_2d[:3,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [74]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
arr_2d[:3, ::2]

array([[ 5, 15],
       [20, 30],
       [35, 45]])

In [84]:
arr_2d[:3, 2::]

array([[15],
       [30],
       [45]])

In [76]:
grid = np.arange(1,13).reshape(3,4)
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
grid=grid.reshape(4,3)
grid

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
grid=grid.reshape(2,6)
grid

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [81]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [82]:
#row axis=0 (vertical)
np.concatenate([grid,grid])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [83]:
#colome axis=1 (horizontal)
np.concatenate([grid,grid],axis=1)

array([[ 1,  2,  3,  4,  5,  6,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12,  7,  8,  9, 10, 11, 12]])

In [85]:
#First split until index 3
#then split from 3 to 5 (3,4)
# other be in x3
x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [86]:
grid = np.arange(16).reshape((4, 4))
print(grid)
print("\n")
#vsplit -> vertical split (aross row) men 2 row only  for two list upper ,lower
upper, lower = np.vsplit(grid, [2])
print(upper)
print("\n")
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [87]:
grid = np.arange(16).reshape((4, 4))
print(grid)
print("\n")
#vsplit -> horzental split (aross colunm) mean 2 colunm only  for two left,right
left, right = np.hsplit(grid, [2])
print(left)
print("\n")
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [100]:
grades = np.array([
   [55, 72, 39],
   [90, 56, 80]
])

#avg
student_sums = np.sum(grades, axis=1)
student_averages = student_sums / grades.shape[1]
print("the avg of each student",student_averages)

#highest grade
subject_highest = np.max(grades, axis=0)
print("the max in Math,Science,English", subject_highest)

#overall avg
total_sum = np.sum(grades)
total_elem = grades.size
overall_avg = total_sum / total_elem
print("the over all of all student is " ,overall_avg)

the avg of each student [55.33333333 75.33333333]
the max in Math,Science,English [90 72 80]
the over all of all student is  65.33333333333333
